# Generated by Django 2.1.2 on 2018-12-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierlist', '0002_tier_fighters'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='first_appearance',
            field=models.CharField(default='SSB64', max_length=30),
        ),
        migrations.AddField(
            model_name='fighter',
            name='origin_game',
            field=models.CharField(default='Super Mario', max_length=30),
        ),
        migrations.AlterField(
            model_name='tier',
            name='color',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tier',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
