# Generated by Django 2.1.2 on 2018-12-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.IntegerField(max_length=1, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=22)),
                ('color', models.IntegerField(max_length=6)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
